name: build

on: 
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: echo "running build..."
      - name: check HEAD
        run: |
          git rev-parse HEAD
          git branch --show-current

