name: build

on: 
  workflow_dispatch:
    inputs:
      commit:
        description: 'Branch or commit to build'
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "running build..."
      - name: log github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: log env
        run: env
